### ISSUE TITLE
My bar disappear

### ISSUE THREAD

**Issue by LaPlanta01** [jamessouth/polybar-nightlight#1]
Ubuntu 22.04

If i write the module on my config file and reload polybar, my bar just dissapear, i don't know what could be happening. I have the three necessary files. I don't know if it's important but i have amd gpu

**Comment by jamessouth** [comment]
Hi @LaPlanta01, sorry for the wait, I just recently saw this. This module is pretty simple and only uses common Linux commands and shell scripting, so I can't imagine that it wouldn't work on Ubuntu or that your GPU would be an issue. Please check the following:

+ you're on `X` and not `Wayland` - I have not tried or tested this on `Wayland`
+ you can run the `xrandr` command in the terminal
+ you have tried to [debug your polybar](https://github.com/polybar/polybar/wiki/Debugging-your-Config) - if your bar is crashing there should be error logs; what do they say?
+ you followed the documentation carefully - please double-check that you did everything as instructed in the README

Apart from that, since this module is so simple and I think it ought to work for just about any Linux user on X, the only other thing I can think of is that there is some problem with you using IPC. Did you try the other instructions for polling on an interval instead of using IPC? Could you try another module that uses IPC like [polybar-quotation](https://github.com/pikulo-kama/polybar-quotation) and see if that works?

**Comment by jamessouth** [comment]
no response, closing
